"""Curated ICD-O-3 topography and morphology code reference tables.

These tables are not an exhaustive ICD-O-3 dictionary but cover the
codes most commonly encountered in adult oncology. They are used both
by the diagnosis summary writer to label codes with human-readable text
and by the Pass-0 coding pass to give the LLM a preferred-code list.
"""

from __future__ import annotations


TOPOGRAPHY_PREFIX: dict[str, str] = {
    "C00": "Lip",
    "C01": "Base of tongue",
    "C02": "Other and unspecified parts of tongue",
    "C03": "Gum",
    "C04": "Floor of mouth",
    "C05": "Palate",
    "C06": "Other and unspecified parts of mouth",
    "C07": "Parotid gland",
    "C08": "Other and unspecified major salivary glands",
    "C09": "Tonsil",
    "C10": "Oropharynx",
    "C11": "Nasopharynx",
    "C12": "Pyriform sinus",
    "C13": "Hypopharynx",
    "C14": "Other and ill-defined sites in lip, oral cavity and pharynx",
    "C15": "Esophagus",
    "C16": "Stomach",
    "C17": "Small intestine",
    "C18": "Colon",
    "C19": "Rectosigmoid junction",
    "C20": "Rectum",
    "C21": "Anus and anal canal",
    "C22": "Liver and intrahepatic bile ducts",
    "C23": "Gallbladder",
    "C24": "Other and unspecified parts of biliary tract",
    "C25": "Pancreas",
    "C26": "Other and ill-defined digestive organs",
    "C30": "Nasal cavity and middle ear",
    "C31": "Accessory sinuses",
    "C32": "Larynx",
    "C33": "Trachea",
    "C34": "Bronchus and lung",
    "C37": "Thymus",
    "C38": "Heart, mediastinum and pleura",
    "C39": "Other and ill-defined respiratory and intrathoracic organs",
    "C40": "Bones, joints and articular cartilage of limbs",
    "C41": "Bones, joints and articular cartilage of other sites",
    "C42": "Hematopoietic and reticuloendothelial systems",
    "C44": "Skin",
    "C45": "Pleura",
    "C47": "Peripheral nerves and autonomic nervous system",
    "C48": "Retroperitoneum and peritoneum",
    "C49": "Connective, subcutaneous and other soft tissues",
    "C50": "Breast",
    "C51": "Vulva",
    "C52": "Vagina",
    "C53": "Cervix uteri",
    "C54": "Corpus uteri",
    "C55": "Uterus, NOS",
    "C56": "Ovary",
    "C57": "Other and unspecified female genital organs",
    "C58": "Placenta",
    "C60": "Penis",
    "C61": "Prostate gland",
    "C62": "Testis",
    "C63": "Other and unspecified male genital organs",
    "C64": "Kidney",
    "C65": "Renal pelvis",
    "C66": "Ureter",
    "C67": "Bladder",
    "C68": "Other and unspecified urinary organs",
    "C69": "Eye and adnexa",
    "C70": "Meninges",
    "C71": "Brain",
    "C72": "Spinal cord, cranial nerves, and other parts of CNS",
    "C73": "Thyroid gland",
    "C74": "Adrenal gland",
    "C75": "Other endocrine glands and related structures",
    "C76": "Other and ill-defined sites",
    "C77": "Lymph nodes",
    "C80": "Unknown primary site",
}


TOPOGRAPHY_EXACT: dict[str, str] = {
    "C15.0": "Cervical esophagus",
    "C15.1": "Thoracic esophagus",
    "C15.2": "Abdominal esophagus",
    "C15.3": "Upper third of esophagus",
    "C15.4": "Middle third of esophagus",
    "C15.5": "Lower third of esophagus",
    "C15.8": "Overlapping lesion of esophagus",
    "C15.9": "Esophagus, NOS",
    "C16.0": "Cardia, NOS",
    "C16.1": "Fundus of stomach",
    "C16.2": "Body of stomach",
    "C16.3": "Gastric antrum",
    "C16.4": "Pylorus",
    "C16.5": "Lesser curvature of stomach, NOS",
    "C16.6": "Greater curvature of stomach, NOS",
    "C16.8": "Overlapping lesion of stomach",
    "C16.9": "Stomach, NOS",
    "C17.0": "Duodenum",
    "C17.1": "Jejunum",
    "C17.2": "Ileum",
    "C17.3": "Meckel diverticulum",
    "C17.8": "Overlapping lesion of small intestine",
    "C17.9": "Small intestine, NOS",
    "C18.0": "Cecum",
    "C18.1": "Appendix",
    "C18.2": "Ascending colon",
    "C18.3": "Hepatic flexure of colon",
    "C18.4": "Transverse colon",
    "C18.5": "Splenic flexure of colon",
    "C18.6": "Descending colon",
    "C18.7": "Sigmoid colon",
    "C18.8": "Overlapping lesion of colon",
    "C18.9": "Colon, NOS",
    "C19.9": "Rectosigmoid junction",
    "C20.9": "Rectum, NOS",
    "C21.0": "Anus, NOS",
    "C21.1": "Anal canal",
    "C21.2": "Cloacogenic zone",
    "C21.8": "Overlapping lesion of rectum, anus and anal canal",
    "C22.0": "Liver",
    "C22.1": "Intrahepatic bile duct",
    "C22.9": "Liver, NOS",
    "C23.9": "Gallbladder",
    "C24.0": "Extrahepatic bile duct",
    "C24.1": "Ampulla of Vater",
    "C24.9": "Biliary tract, NOS",
    "C25.0": "Head of pancreas",
    "C25.1": "Body of pancreas",
    "C25.2": "Tail of pancreas",
    "C25.3": "Pancreatic duct",
    "C25.4": "Islets of Langerhans",
    "C25.7": "Other specified parts of pancreas",
    "C25.8": "Overlapping lesion of pancreas",
    "C25.9": "Pancreas, NOS",
    "C32.0": "Glottis",
    "C32.1": "Supraglottis",
    "C32.2": "Subglottis",
    "C32.9": "Larynx, NOS",
    "C34.0": "Main bronchus",
    "C34.1": "Upper lobe, lung",
    "C34.2": "Middle lobe, lung",
    "C34.3": "Lower lobe, lung",
    "C34.8": "Overlapping lesion of lung",
    "C34.9": "Lung, NOS",
    "C37.9": "Thymus",
    "C38.4": "Pleura, NOS",
    "C40.0": "Long bones of upper limb, scapula and associated joints",
    "C40.2": "Long bones of lower limb and associated joints",
    "C41.0": "Bones of skull and face and associated joints",
    "C41.1": "Mandible",
    "C41.2": "Vertebral column",
    "C41.4": "Pelvic bones, sacrum, coccyx and associated joints",
    "C42.0": "Blood",
    "C42.1": "Bone marrow",
    "C42.2": "Spleen",
    "C42.3": "Reticuloendothelial system, NOS",
    "C42.4": "Hematopoietic system, NOS",
    "C44.0": "Skin of lip, NOS",
    "C44.1": "Eyelid",
    "C44.2": "External ear",
    "C44.3": "Skin of other and unspecified parts of face",
    "C44.4": "Skin of scalp and neck",
    "C44.5": "Skin of trunk",
    "C44.6": "Skin of upper limb and shoulder",
    "C44.7": "Skin of lower limb and hip",
    "C44.8": "Overlapping lesion of skin",
    "C44.9": "Skin, NOS",
    "C45.0": "Pleura, parietal",
    "C45.1": "Pleura, visceral",
    "C45.7": "Other specified sites of pleura",
    "C45.9": "Mesothelium, NOS (pleura)",
    "C48.0": "Retroperitoneum",
    "C48.1": "Specified parts of peritoneum",
    "C48.2": "Peritoneum, NOS",
    "C49.1": "Connective and soft tissue of upper limb and shoulder",
    "C49.2": "Connective and soft tissue of lower limb and hip",
    "C49.3": "Connective and soft tissue of thorax",
    "C49.4": "Connective and soft tissue of abdomen",
    "C49.5": "Connective and soft tissue of pelvis",
    "C49.6": "Connective and soft tissue of trunk, NOS",
    "C49.9": "Connective, subcutaneous and other soft tissues, NOS",
    "C50.0": "Nipple",
    "C50.1": "Central portion of breast",
    "C50.2": "Upper-inner quadrant of breast",
    "C50.3": "Lower-inner quadrant of breast",
    "C50.4": "Upper-outer quadrant of breast",
    "C50.5": "Lower-outer quadrant of breast",
    "C50.6": "Axillary tail of breast",
    "C50.8": "Overlapping lesion of breast",
    "C50.9": "Breast, NOS",
    "C53.0": "Endocervix",
    "C53.1": "Exocervix",
    "C53.8": "Overlapping lesion of cervix uteri",
    "C53.9": "Cervix uteri",
    "C54.0": "Isthmus uteri",
    "C54.1": "Endometrium",
    "C54.2": "Myometrium",
    "C54.3": "Fundus uteri",
    "C54.8": "Overlapping lesion of corpus uteri",
    "C54.9": "Corpus uteri",
    "C56.9": "Ovary",
    "C57.0": "Fallopian tube",
    "C61.9": "Prostate gland",
    "C62.0": "Undescended testis",
    "C62.1": "Descended testis",
    "C62.9": "Testis, NOS",
    "C64.9": "Kidney, NOS",
    "C65.9": "Renal pelvis",
    "C66.9": "Ureter",
    "C67.0": "Trigone of bladder",
    "C67.1": "Dome of bladder",
    "C67.2": "Lateral wall of bladder",
    "C67.3": "Anterior wall of bladder",
    "C67.4": "Posterior wall of bladder",
    "C67.5": "Bladder neck",
    "C67.6": "Ureteric orifice",
    "C67.7": "Urachus",
    "C67.8": "Overlapping lesion of bladder",
    "C67.9": "Bladder, NOS",
    "C70.0": "Cerebral meninges",
    "C70.1": "Spinal meninges",
    "C70.9": "Meninges, NOS",
    "C71.0": "Cerebrum",
    "C71.1": "Frontal lobe",
    "C71.2": "Temporal lobe",
    "C71.3": "Parietal lobe",
    "C71.4": "Occipital lobe",
    "C71.5": "Ventricle, NOS",
    "C71.6": "Cerebellum, NOS",
    "C71.7": "Brain stem",
    "C71.8": "Overlapping lesion of brain",
    "C71.9": "Brain, NOS",
    "C72.0": "Spinal cord",
    "C73.9": "Thyroid gland",
    "C74.9": "Adrenal gland, NOS",
    "C76.0": "Head, face or neck, NOS",
    "C76.1": "Thorax, NOS",
    "C76.2": "Abdomen, NOS",
    "C76.3": "Pelvis, NOS",
    "C77.0": "Lymph nodes of head, face and neck",
    "C77.1": "Intrathoracic lymph nodes",
    "C77.2": "Intra-abdominal lymph nodes",
    "C77.3": "Lymph nodes of axilla or arm",
    "C77.4": "Lymph nodes of inguinal region or leg",
    "C77.5": "Pelvic lymph nodes",
    "C77.8": "Lymph nodes of multiple regions",
    "C77.9": "Lymph node, NOS",
    "C80.9": "Unknown primary site",
}


MORPHOLOGY: dict[str, str] = {
    "8000": "Neoplasm, malignant",
    "8001": "Tumor cells, malignant",
    "8010": "Carcinoma, NOS",
    "8012": "Large cell carcinoma, NOS",
    "8013": "Large cell neuroendocrine carcinoma",
    "8020": "Carcinoma, undifferentiated, NOS",
    "8021": "Carcinoma, anaplastic, NOS",
    "8041": "Small cell carcinoma, NOS",
    "8045": "Combined small cell carcinoma",
    "8046": "Non-small cell carcinoma",
    "8050": "Papillary carcinoma, NOS",
    "8060": "Squamous papillomatosis",
    "8070": "Squamous cell carcinoma, NOS",
    "8071": "Squamous cell carcinoma, keratinizing, NOS",
    "8072": "Squamous cell carcinoma, large cell, nonkeratinizing, NOS",
    "8074": "Squamous cell carcinoma, spindle cell",
    "8077": "Squamous intraepithelial neoplasia, grade III",
    "8083": "Basaloid squamous cell carcinoma",
    "8090": "Basal cell carcinoma, NOS",
    "8094": "Basosquamous carcinoma",
    "8120": "Transitional cell carcinoma, NOS",
    "8130": "Papillary transitional cell carcinoma",
    "8140": "Adenocarcinoma, NOS",
    "8141": "Scirrhous adenocarcinoma",
    "8144": "Adenocarcinoma, intestinal type",
    "8145": "Carcinoma, diffuse type",
    "8160": "Cholangiocarcinoma",
    "8170": "Hepatocellular carcinoma, NOS",
    "8200": "Adenoid cystic carcinoma",
    "8210": "Adenocarcinoma in adenomatous polyp",
    "8211": "Tubular adenocarcinoma",
    "8230": "Solid carcinoma, NOS",
    "8240": "Carcinoid tumor, NOS",
    "8246": "Neuroendocrine carcinoma, NOS",
    "8249": "Atypical carcinoid",
    "8250": "Bronchiolo-alveolar adenocarcinoma, NOS",
    "8253": "Mucinous bronchiolo-alveolar carcinoma",
    "8255": "Adenocarcinoma with mixed subtypes",
    "8260": "Papillary adenocarcinoma, NOS",
    "8265": "Micropapillary adenocarcinoma",
    "8310": "Clear cell adenocarcinoma, NOS",
    "8312": "Renal cell carcinoma, NOS",
    "8317": "Renal cell carcinoma, chromophobe type",
    "8318": "Renal cell carcinoma, sarcomatoid",
    "8323": "Mixed cell adenocarcinoma",
    "8340": "Papillary thyroid carcinoma, follicular variant",
    "8341": "Papillary microcarcinoma (thyroid)",
    "8380": "Endometrioid adenocarcinoma, NOS",
    "8430": "Mucoepidermoid carcinoma",
    "8441": "Serous cystadenocarcinoma, NOS",
    "8460": "Papillary serous cystadenocarcinoma",
    "8470": "Mucinous cystadenocarcinoma, NOS",
    "8480": "Mucinous adenocarcinoma",
    "8490": "Signet ring cell carcinoma",
    "8500": "Infiltrating duct carcinoma, NOS",
    "8502": "Secretory carcinoma of breast",
    "8510": "Medullary carcinoma, NOS",
    "8520": "Lobular carcinoma, NOS",
    "8522": "Infiltrating duct and lobular carcinoma",
    "8530": "Inflammatory carcinoma",
    "8550": "Acinar cell carcinoma",
    "8560": "Adenosquamous carcinoma",
    "8720": "Malignant melanoma, NOS",
    "8721": "Nodular melanoma",
    "8742": "Lentigo maligna melanoma",
    "8743": "Superficial spreading melanoma",
    "8744": "Acral lentiginous melanoma",
    "8745": "Desmoplastic melanoma",
    "8770": "Mixed epithelioid and spindle cell melanoma",
    "8800": "Sarcoma, NOS",
    "8810": "Fibrosarcoma, NOS",
    "8830": "Malignant fibrous histiocytoma / undifferentiated pleomorphic sarcoma",
    "8832": "Dermatofibrosarcoma protuberans",
    "8850": "Liposarcoma, NOS",
    "8852": "Myxoid liposarcoma",
    "8854": "Pleomorphic liposarcoma",
    "8858": "Dedifferentiated liposarcoma",
    "8890": "Leiomyosarcoma, NOS",
    "8900": "Rhabdomyosarcoma, NOS",
    "8910": "Embryonal rhabdomyosarcoma, NOS",
    "8920": "Alveolar rhabdomyosarcoma",
    "8930": "Endometrial stromal sarcoma",
    "8936": "Gastrointestinal stromal tumor",
    "8960": "Nephroblastoma (Wilms tumor)",
    "9040": "Synovial sarcoma, NOS",
    "9050": "Mesothelioma, malignant",
    "9061": "Seminoma, NOS",
    "9070": "Embryonal carcinoma, NOS",
    "9071": "Yolk sac tumor",
    "9080": "Teratoma, malignant, NOS",
    "9085": "Mixed germ cell tumor",
    "9100": "Choriocarcinoma, NOS",
    "9120": "Angiosarcoma",
    "9140": "Kaposi sarcoma",
    "9180": "Osteosarcoma, NOS",
    "9220": "Chondrosarcoma, NOS",
    "9260": "Ewing sarcoma",
    "9370": "Chordoma",
    "9380": "Glioma, malignant",
    "9382": "Mixed glioma (oligoastrocytoma)",
    "9391": "Ependymoma, NOS",
    "9400": "Astrocytoma, NOS",
    "9401": "Astrocytoma, anaplastic",
    "9421": "Pilocytic astrocytoma",
    "9440": "Glioblastoma, NOS",
    "9450": "Oligodendroglioma, NOS",
    "9451": "Oligodendroglioma, anaplastic",
    "9470": "Medulloblastoma, NOS",
    "9530": "Meningioma, NOS",
    "9540": "Malignant peripheral nerve sheath tumor",
    "9590": "Malignant lymphoma, NOS",
    "9650": "Hodgkin lymphoma, NOS",
    "9663": "Hodgkin lymphoma, nodular sclerosis, NOS",
    "9670": "Small lymphocytic lymphoma (SLL)",
    "9671": "Lymphoplasmacytic lymphoma",
    "9673": "Mantle cell lymphoma",
    "9679": "Mediastinal large B-cell lymphoma",
    "9680": "Diffuse large B-cell lymphoma, NOS (DLBCL)",
    "9687": "Burkitt lymphoma",
    "9690": "Follicular lymphoma, NOS",
    "9691": "Follicular lymphoma, grade 2",
    "9695": "Follicular lymphoma, grade 1",
    "9698": "Follicular lymphoma, grade 3",
    "9699": "Marginal zone B-cell lymphoma, NOS",
    "9700": "Mycosis fungoides",
    "9702": "Mature T-cell lymphoma, NOS",
    "9714": "Anaplastic large cell lymphoma, T/null cell",
    "9728": "B lymphoblastic lymphoma",
    "9729": "T lymphoblastic lymphoma",
    "9731": "Plasmacytoma of bone",
    "9732": "Plasma cell myeloma",
    "9734": "Extramedullary plasmacytoma",
    "9740": "Mast cell sarcoma",
    "9751": "Langerhans cell histiocytosis",
    "9761": "Waldenstrom macroglobulinemia",
    "9800": "Leukemia, NOS",
    "9811": "B lymphoblastic leukemia/lymphoma",
    "9823": "Chronic lymphocytic leukemia / small lymphocytic lymphoma (CLL/SLL)",
    "9826": "Burkitt cell leukemia",
    "9837": "T lymphoblastic leukemia/lymphoma",
    "9861": "Acute myeloid leukemia, NOS",
    "9863": "Chronic myeloid leukemia, BCR/ABL positive",
    "9866": "Acute promyelocytic leukemia with t(15;17)",
    "9867": "Acute myelomonocytic leukemia",
    "9871": "Acute myeloid leukemia with inv(16)",
    "9891": "Acute monocytic leukemia",
    "9895": "Acute myeloid leukemia with myelodysplasia-related changes",
    "9920": "Therapy-related acute myeloid leukemia, NOS",
    "9930": "Myeloid sarcoma",
    "9940": "Hairy cell leukemia",
    "9945": "Chronic myelomonocytic leukemia",
    "9950": "Polycythemia vera",
    "9960": "Chronic myeloproliferative disease, NOS",
    "9962": "Essential thrombocythemia",
    "9989": "Myelodysplastic syndrome, NOS",
}
