"""Pass 4: Follow-up, outcomes, and narrative text summaries."""

from __future__ import annotations

from typing import Any
import logging

from naaccr_pipeline.config import PipelineConfig
from naaccr_pipeline.dictionary.loader import NAACCRDictionary, NAACCRDataItem
from naaccr_pipeline.dictionary.code_resolver import CodeResolver
from naaccr_pipeline.extraction.base import (
    BaseExtractionPass,
    ExtractionResult,
    _CodeResolverAdapter,
)
from naaccr_pipeline.extraction.prompts.followup import (
    PASS4_SYSTEM_PROMPT,
    PASS4_USER_TEMPLATE,
    TEXT_SUMMARY_SYSTEM_PROMPT,
    TEXT_SUMMARY_USER_TEMPLATE,
)
from naaccr_pipeline.llm.client import VLLMClient
from naaccr_pipeline.llm.structured_output import SchemaBuilder

logger = logging.getLogger(__name__)

# Confidence threshold above which an item is considered fully resolved.
_HIGH_CONFIDENCE_THRESHOLD = 0.9

# Maximum characters of aggregated text to send for narrative summaries.
_MAX_AGGREGATE_TEXT_CHARS = 60_000

# Mapping from chunk types to the text item numbers they are most
# relevant for.  Used when aggregating text for narrative summaries.
_CHUNK_TYPE_TO_TEXT_ITEMS: dict[str, list[int]] = {
    "pathology": [2570],          # Text--DX Proc--Path
    "radiology": [2530],          # Text--DX Proc--X-ray/Scan
    "operative": [2560, 2610],    # Text--DX Proc--Op, RX Text--Surgery
    "lab": [2550],                # Text--DX Proc--Lab Tests
    "consult": [2520, 2600],      # Text--DX Proc--PE, Text--Staging
    "progress_note": [2520],      # Text--DX Proc--PE
    "discharge_summary": [2680],  # Text--Remarks
}


class Pass4Followup(BaseExtractionPass):
    """Extract follow-up/outcome data and generate narrative text summaries.

    This pass has two distinct phases:

    1. **Follow-up coded items** -- vital status, date of last contact,
       cancer status, cause of death.  These are extracted from the most
       recent chunks using the standard chunk-prioritised approach.

    2. **Narrative text summaries** -- NAACCR text fields (2520-2680) that
       contain free-text clinical summaries.  These are generated by
       aggregating text from all relevant chunks and sending it to the LLM
       with a specialised narrative-writing prompt.
    """

    PASS_NUMBER = 4
    CHUNK_PRIORITY = [
        "progress_note",
        "discharge_summary",
        "consult",
        "operative",
        "pathology",
        "radiology",
        "lab",
        "mixed",
    ]

    FOLLOWUP_ITEMS = [
        1750,  # Date of Last Contact
        1760,  # Vital Status
        1770,  # Cancer Status
        1772,  # Date of Last Cancer Status
        1790,  # Follow-Up Source
        1910,  # Cause of Death
    ]

    TEXT_ITEMS = [
        2520,  # Text--DX Proc--PE
        2530,  # Text--DX Proc--X-ray/Scan
        2540,  # Text--DX Proc--Scopes
        2550,  # Text--DX Proc--Lab Tests
        2560,  # Text--DX Proc--Op
        2570,  # Text--DX Proc--Path
        2580,  # Text--Primary Site Title
        2590,  # Text--Histology Title
        2600,  # Text--Staging
        2610,  # RX Text--Surgery
        2620,  # RX Text--Radiation (Beam)
        2630,  # RX Text--Radiation Other
        2640,  # RX Text--Chemo
        2650,  # RX Text--Hormone
        2660,  # RX Text--BRM
        2670,  # RX Text--Other
        2680,  # Text--Remarks
    ]

    # ------------------------------------------------------------------
    # Target items
    # ------------------------------------------------------------------

    def get_target_items(
        self, prior_results: dict[int, ExtractionResult]
    ) -> list[NAACCRDataItem]:
        """Return follow-up items plus text summary items."""
        all_nums = self.FOLLOWUP_ITEMS + self.TEXT_ITEMS
        return [
            item
            for num in all_nums
            if (item := self._dict.get_item(num)) is not None
        ]

    # ------------------------------------------------------------------
    # Prompt construction (base-class interface -- used for follow-up)
    # ------------------------------------------------------------------

    def build_prompt(
        self,
        chunk: Any,
        target_items: list[NAACCRDataItem],
        prior_results: dict[int, ExtractionResult],
    ) -> tuple[str, str]:
        """Build the follow-up extraction prompt for a single chunk.

        Used by ``_extract_followup_items`` for the coded follow-up items.
        """
        code_blocks: list[str] = []
        for item in target_items:
            codes_text = self._resolver.get_valid_codes_prompt(item.item_number)
            if codes_text:
                code_blocks.append(
                    f"- {item.name} (Item {item.item_number}): {codes_text}"
                )
            else:
                if item.data_type == "date":
                    code_blocks.append(
                        f"- {item.name} (Item {item.item_number}): YYYYMMDD format"
                    )
                elif item.data_type == "digits":
                    code_blocks.append(
                        f"- {item.name} (Item {item.item_number}): "
                        f"{item.length}-digit number. {item.allowable_values or ''}"
                    )
                else:
                    code_blocks.append(
                        f"- {item.name} (Item {item.item_number}): "
                        f"max {item.length} characters. {item.allowable_values or ''}"
                    )

        note_type = getattr(chunk, "chunk_type", "unknown")
        note_date = getattr(chunk, "document_date", "unknown")

        user = PASS4_USER_TEMPLATE.format(
            chunk_text=chunk.text,
            code_reference="\n".join(code_blocks),
            note_type=note_type,
            note_date=note_date,
        )
        return PASS4_SYSTEM_PROMPT, user

    # ------------------------------------------------------------------
    # Core execution (overrides BaseExtractionPass.run)
    # ------------------------------------------------------------------

    async def run(
        self,
        chunks: list[Any],
        prior_results: dict[int, ExtractionResult],
    ) -> list[ExtractionResult]:
        """Execute two-phase extraction: coded follow-up then narrative text.

        Phase 1 -- Follow-up coded items
            Uses the standard chunk-priority extraction from the newest
            chunks (progress notes, discharge summaries) to populate vital
            status, date of last contact, cancer status, etc.

        Phase 2 -- Narrative text summaries
            Aggregates text from all chunks by type and sends a single LLM
            call to produce the NAACCR text-field summaries (items 2520-2680).

        Results from both phases are merged and returned.
        """
        merged = dict(prior_results)

        # Phase 1: coded follow-up items
        followup_results = await self._extract_followup_items(chunks, merged)
        merged = self._merge_results(merged, followup_results)

        # Phase 2: narrative text summaries
        text_results = await self._generate_text_summaries(chunks, merged)
        merged = self._merge_results(merged, text_results)

        return list(merged.values())

    # ------------------------------------------------------------------
    # Phase 1: Follow-up coded items
    # ------------------------------------------------------------------

    async def _extract_followup_items(
        self,
        chunks: list[Any],
        prior_results: dict[int, ExtractionResult],
    ) -> list[ExtractionResult]:
        """Extract coded follow-up items using the standard approach.

        Filters to only the follow-up item numbers, prioritises chunks
        (newest first for this pass), and processes each chunk/batch.
        """
        # Resolve item numbers, skipping high-confidence results.
        items: list[NAACCRDataItem] = []
        for num in self.FOLLOWUP_ITEMS:
            item = self._dict.get_item(num)
            if item is None:
                continue
            existing = prior_results.get(num)
            if existing is not None and existing.confidence >= _HIGH_CONFIDENCE_THRESHOLD:
                continue
            items.append(item)

        if not items:
            logger.info(
                "Pass %d: all follow-up items already at high confidence.",
                self.PASS_NUMBER,
            )
            return []

        ordered_chunks = self._prioritize_chunks(chunks)
        if not ordered_chunks:
            logger.warning(
                "Pass %d: no chunks available for follow-up extraction.",
                self.PASS_NUMBER,
            )
            return []

        logger.info(
            "Pass %d: extracting %d follow-up items from %d chunks.",
            self.PASS_NUMBER,
            len(items),
            len(ordered_chunks),
        )

        items_per_call = self._llm.model_profile.items_per_call
        batches = self._split_items_into_batches(items, items_per_call)

        all_results: list[ExtractionResult] = []
        for chunk in ordered_chunks:
            for batch in batches:
                try:
                    new_results = await self._extract_from_chunk(
                        chunk, batch, prior_results
                    )
                    all_results.extend(new_results)
                except Exception:
                    logger.exception(
                        "Pass %d: error extracting follow-up from chunk %s",
                        self.PASS_NUMBER,
                        getattr(chunk, "chunk_id", "?"),
                    )

        return all_results

    # ------------------------------------------------------------------
    # Phase 2: Narrative text summaries
    # ------------------------------------------------------------------

    async def _generate_text_summaries(
        self,
        chunks: list[Any],
        prior_results: dict[int, ExtractionResult],
    ) -> list[ExtractionResult]:
        """Generate narrative text summaries from all chunks.

        Aggregates clinical text from chunks by type, composing a combined
        document that is sent to the LLM with the text-summary prompt.
        The LLM produces a JSON response keyed by the xml_id of each text
        item.

        Steps
        -----
        1. Filter text items that are not already at high confidence.
        2. Aggregate chunk text by type, respecting the character budget.
        3. Build a schema for the text items (free-text values).
        4. Call the LLM with the TEXT_SUMMARY_SYSTEM_PROMPT.
        5. Parse response into ExtractionResult objects.
        """
        # Resolve text item numbers, skipping high-confidence results.
        text_items: list[NAACCRDataItem] = []
        for num in self.TEXT_ITEMS:
            item = self._dict.get_item(num)
            if item is None:
                continue
            existing = prior_results.get(num)
            if existing is not None and existing.confidence >= _HIGH_CONFIDENCE_THRESHOLD:
                continue
            text_items.append(item)

        if not text_items:
            logger.info(
                "Pass %d: all text items already at high confidence.",
                self.PASS_NUMBER,
            )
            return []

        if not chunks:
            logger.warning(
                "Pass %d: no chunks available for text summaries.",
                self.PASS_NUMBER,
            )
            return []

        # Aggregate text from chunks, organised by chunk type.
        aggregated_text = self._aggregate_chunk_text(chunks)
        if not aggregated_text:
            logger.warning(
                "Pass %d: no usable text in chunks for summaries.",
                self.PASS_NUMBER,
            )
            return []

        logger.info(
            "Pass %d: generating narrative summaries for %d text items "
            "(%d chars of aggregated text).",
            self.PASS_NUMBER,
            len(text_items),
            len(aggregated_text),
        )

        # Build the schema -- text items are free-text fields.
        text_schema = self._build_text_summary_schema(text_items)

        user_prompt = TEXT_SUMMARY_USER_TEMPLATE.format(all_text=aggregated_text)

        response = await self._llm.extract(
            TEXT_SUMMARY_SYSTEM_PROMPT, user_prompt, text_schema
        )

        if response.get("_error"):
            logger.warning(
                "LLM error generating text summaries: %s",
                response.get("_message", "unknown"),
            )
            return []

        return self._parse_text_summary_response(response, text_items, chunks)

    # ------------------------------------------------------------------
    # Text aggregation helpers
    # ------------------------------------------------------------------

    def _aggregate_chunk_text(self, chunks: list[Any]) -> str:
        """Aggregate text from all chunks, grouped by document type.

        Each section is labelled with the document type and date to give
        the LLM context about where each piece of text comes from.  The
        output is truncated to ``_MAX_AGGREGATE_TEXT_CHARS``.
        """
        # Group chunks by type.
        by_type: dict[str, list[Any]] = {}
        for chunk in chunks:
            ctype = getattr(chunk, "chunk_type", "other")
            by_type.setdefault(ctype, []).append(chunk)

        # Build sections in a clinically logical order.
        type_order = [
            "pathology",
            "operative",
            "radiology",
            "consult",
            "discharge_summary",
            "progress_note",
            "lab",
            "mixed",
        ]
        # Include any types not in the canonical order.
        seen = set(type_order)
        for ctype in by_type:
            if ctype not in seen:
                type_order.append(ctype)

        sections: list[str] = []
        total_chars = 0

        for ctype in type_order:
            chunk_list = by_type.get(ctype)
            if not chunk_list:
                continue

            # Sort by date (oldest first) within each type.
            chunk_list.sort(
                key=lambda c: getattr(c, "document_date", "") or ""
            )

            label = ctype.replace("_", " ").title()
            for chunk in chunk_list:
                doc_date = getattr(chunk, "document_date", "unknown")
                text = getattr(chunk, "text", "").strip()
                if not text:
                    continue

                header = f"--- {label} (date: {doc_date}) ---"
                section = f"{header}\n{text}\n"

                # Respect the character budget.
                if total_chars + len(section) > _MAX_AGGREGATE_TEXT_CHARS:
                    remaining = _MAX_AGGREGATE_TEXT_CHARS - total_chars
                    if remaining > len(header) + 100:
                        # Include a truncated version.
                        section = f"{header}\n{text[:remaining - len(header) - 20]}\n[truncated]\n"
                        sections.append(section)
                        total_chars += len(section)
                    break
                sections.append(section)
                total_chars += len(section)

            if total_chars >= _MAX_AGGREGATE_TEXT_CHARS:
                break

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Schema for text summaries
    # ------------------------------------------------------------------

    def _build_text_summary_schema(
        self, text_items: list[NAACCRDataItem]
    ) -> dict:
        """Build a JSON schema for the narrative text summary response.

        Each text item becomes a JSON field with a value (free text up to
        4000 chars), confidence, and evidence.
        """
        properties: dict[str, dict] = {}
        required: list[str] = []

        for item in text_items:
            field_name = item.xml_id if item.xml_id else f"item_{item.item_number}"
            # Text summary fields allow up to 4000 characters.
            max_len = max(item.length, 4000) if item.length > 0 else 4000
            properties[field_name] = {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string",
                        "maxLength": max_len,
                    },
                    "confidence": {
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1,
                    },
                    "evidence": {
                        "type": "string",
                        "maxLength": 200,
                    },
                },
                "required": ["value", "confidence", "evidence"],
            }
            required.append(field_name)

        return {
            "type": "object",
            "properties": properties,
            "required": required,
        }

    # ------------------------------------------------------------------
    # Response parsing for text summaries
    # ------------------------------------------------------------------

    def _parse_text_summary_response(
        self,
        response: dict,
        text_items: list[NAACCRDataItem],
        chunks: list[Any],
    ) -> list[ExtractionResult]:
        """Parse the LLM text-summary response into ExtractionResult objects.

        Text summaries do not go through code resolution -- the value is
        used as-is.  Confidence is taken directly from the LLM response.
        The source chunk is attributed as "aggregated" since the summary
        draws from multiple chunks.
        """
        results: list[ExtractionResult] = []

        # Build a lookup: xml_id -> NAACCRDataItem
        xml_id_map: dict[str, NAACCRDataItem] = {}
        for item in text_items:
            key = item.xml_id if item.xml_id else f"item_{item.item_number}"
            xml_id_map[key] = item

        for field_name, payload in response.items():
            if field_name.startswith("_"):
                continue

            item = xml_id_map.get(field_name)
            if item is None:
                logger.debug(
                    "LLM returned unknown text field '%s'; skipping.", field_name
                )
                continue

            if not isinstance(payload, dict):
                logger.debug(
                    "Unexpected payload type for text field '%s': %s",
                    field_name,
                    type(payload),
                )
                continue

            raw_value = str(payload.get("value", "")).strip()
            confidence = float(payload.get("confidence", 0.0))
            evidence = str(payload.get("evidence", "")).strip()

            if not raw_value:
                continue

            # Truncate to the item's maximum length (if defined).
            if item.length > 0:
                raw_value = raw_value[:item.length]

            results.append(
                ExtractionResult(
                    item_number=item.item_number,
                    item_name=item.name,
                    extracted_value=raw_value,
                    resolved_code=raw_value,  # No code resolution for text fields
                    confidence=round(confidence, 4),
                    evidence_text=evidence[:300],
                    source_chunk_id="aggregated",
                    source_chunk_type="aggregated",
                    pass_number=self.PASS_NUMBER,
                )
            )

        return results
